spring:
  application:
    name: proxi-alert-engine
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql

  data:
    redis:
      host:  127.0.0.1
      port: 6379
      timeout: 60000ms
      jedis:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

  kafka:
    topics:
      user_registered_topic: proxy-sentry-user-registered
      email_topic: email-disaster-alerts-notification
      sms_topic: sms-disaster-alerts-notification
    bootstrap-servers: localhost:9092,localhost:9094,localhost:9095
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        retries: 3

server:
  port: 7000